
workflow:
  rules:
    # This pipeline only runs for tags
    - if: $CI_COMMIT_TAG

stages:
  - build
  - deploy

variables:
  IMAGENAME: 'collaborative-frontend-development-framework'

default:
  before_script:
    - EXP='^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-([0-9a-zA-Z.-]*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$'
    - VERSION=$(echo $CI_COMMIT_TAG | sed -n -E "s/$EXP/\1.\2.\3\4/p")
    - TXT_RED="\e[31m"
    - TXT_CLEAR="\e[0m"

build:
  stage: build
  image: docker:20.10
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo "Building $IMAGENAME - $CI_COMMIT_TAG - $CI_REGISTRY_IMAGE/$IMAGENAME:$VERSION"
    - docker build -m 8g --pull -t $CI_REGISTRY_IMAGE/$IMAGENAME:$VERSION .
    - docker tag $CI_REGISTRY_IMAGE/$IMAGENAME:$VERSION $CI_REGISTRY_IMAGE/$IMAGENAME:latest
    - docker push $CI_REGISTRY_IMAGE/$IMAGENAME:$VERSION
    - docker push $CI_REGISTRY_IMAGE/$IMAGENAME:latest
  rules:
    # Only run this job if a version tag exists
    - if: $CI_COMMIT_TAG =~ /^v?(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      exists:
        - Dockerfile
  tags:
    - unparallel-runner
    - docker
