import Layout, {siteTitle} from "../components/layout/layout";
import Head from "next/head";
import {useSession} from "next-auth/react";
import Login from "../components/login/login";
import Welcome from "../components/welcome/welcome";

export default function Home(){
    const {data: session} = useSession();

    return (
        <Layout home>
            <Head>
                <title>{siteTitle}</title>
                <meta name={"description"} content={"Generated by create next app"}/>
                <link rel={"icon"} href={"/favicon.png"}/>
            </Head>
            {!session ? <Login/> : <Welcome/>}
        </Layout>
    );
}
