import Head from 'next/head';
import Layout, { siteTitle } from '../components/layout';
import utilStyles from '../styles/utils.module.css';
import { getSortedPostsData } from '../lib/posts';
import Link from 'next/link';
import Date from '../components/date';
import {signIn, signOut, useSession} from "next-auth/react";

export async function getStaticProps() {
    const allPostsData = getSortedPostsData();
    return {
        props: {
            allPostsData
        },
    };
}

export default function Home({allPostsData}) {
    const { data: session } = useSession();
    return (
        <Layout home>
            <Head>
                <title>{siteTitle}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {!session ? (
                <>
                    <h4>Not signed in</h4>
                    <br />
                    <button onClick={() => signIn()}>Sign in</button>
                </>
            ) : (
                <>
                    <section className={utilStyles.headingMd}>
                        <p>[Your Self Introduction]</p>
                        <p>
                            (This is a sample website - you’ll be building a site like this on{' '}
                            <a href="https://nextjs.org/learn">our Next.js tutorial</a>.)
                        </p>
                    </section>
                    <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
                        <h2 className={utilStyles.headingLg}>Blog</h2>
                        <ul className={utilStyles.list}>
                            {allPostsData.map(({id, date, title}) => (
                                <li className={utilStyles.listItem} key={id}>
                                    <Link href={`/posts/${id}`}>{title}</Link>
                                    <br/>
                                    <small className={utilStyles.lightText}>
                                        <Date dateString={date}/>
                                    </small>
                                </li>
                            ))}
                        </ul>
                    </section>
                    <div>
                        <h4>Signed in as {session.user.name}</h4>
                        <button onClick={() => signOut()}>Sign out</button>
                    </div>
                </>
            )}
        </Layout>
    );
}
